apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mft-kube-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mqft-kube
    spec:
      containers:
      - name: agentsrc
        image: registry.eu-de.bluemix.net/mft-images/agentredist_mftimagerepo:1.0
        env:
        - name: MQ_QMGR_NAME
          value: "QM1"
        - name: MQ_QMGR_HOST
          value: "159.122.181.5"
        - name: MQ_QMGR_PORT
          value: "31883"
        - name: MQ_QMGR_CHL
          value: "MFT.SVRCONN"
        - name: MFT_AGENT_NAME
          value: "AGENTSRC"
